services:
  task-flow:
    container_name: task-flow_app
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: True
    tty: True
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    env_file:
      - .env