services:
  task_flow_app:
    container_name: task_flow_app
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: True
    tty: True
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env