services:
  task_flow_app:
    container_name: task_flow_app
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: True
    tty: True
    restart: always
    ports:
      - "8005:8005"
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/app
    env_file:
      - .env